// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBilibiliUsers(t *testing.T) {
	t.Parallel()

	query := BilibiliUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBilibiliUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBilibiliUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BilibiliUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBilibiliUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BilibiliUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBilibiliUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BilibiliUserExists(ctx, tx, o.UID)
	if err != nil {
		t.Errorf("Unable to check if BilibiliUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BilibiliUserExists to return true, but got false.")
	}
}

func testBilibiliUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bilibiliUserFound, err := FindBilibiliUser(ctx, tx, o.UID)
	if err != nil {
		t.Error(err)
	}

	if bilibiliUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBilibiliUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BilibiliUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBilibiliUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BilibiliUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBilibiliUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bilibiliUserOne := &BilibiliUser{}
	bilibiliUserTwo := &BilibiliUser{}
	if err = randomize.Struct(seed, bilibiliUserOne, bilibiliUserDBTypes, false, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}
	if err = randomize.Struct(seed, bilibiliUserTwo, bilibiliUserDBTypes, false, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bilibiliUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bilibiliUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BilibiliUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBilibiliUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bilibiliUserOne := &BilibiliUser{}
	bilibiliUserTwo := &BilibiliUser{}
	if err = randomize.Struct(seed, bilibiliUserOne, bilibiliUserDBTypes, false, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}
	if err = randomize.Struct(seed, bilibiliUserTwo, bilibiliUserDBTypes, false, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bilibiliUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bilibiliUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testBilibiliUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBilibiliUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bilibiliUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBilibiliUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBilibiliUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BilibiliUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBilibiliUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BilibiliUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bilibiliUserDBTypes = map[string]string{`UID`: `bigint`, `Counter`: `bigint`, `IsWhitelist`: `boolean`, `BanUntil`: `timestamp with time zone`, `RequestedAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                   = bytes.MinRead
)

func testBilibiliUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bilibiliUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bilibiliUserAllColumns) == len(bilibiliUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBilibiliUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bilibiliUserAllColumns) == len(bilibiliUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BilibiliUser{}
	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bilibiliUserDBTypes, true, bilibiliUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bilibiliUserAllColumns, bilibiliUserPrimaryKeyColumns) {
		fields = bilibiliUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			bilibiliUserAllColumns,
			bilibiliUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BilibiliUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBilibiliUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(bilibiliUserAllColumns) == len(bilibiliUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BilibiliUser{}
	if err = randomize.Struct(seed, &o, bilibiliUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BilibiliUser: %s", err)
	}

	count, err := BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bilibiliUserDBTypes, false, bilibiliUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BilibiliUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BilibiliUser: %s", err)
	}

	count, err = BilibiliUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
